-- 创建 todo 表
CREATE TABLE IF NOT EXISTS `todo` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL COMMENT '待办标题',
    `priority` INT DEFAULT 0 COMMENT '优先级 0-普通 1-重要 2-紧急',
    `completed` INT DEFAULT 0 COMMENT '0-未完成 1-已完成',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待办事项表';
